name: CI/CD Pipeline for Static Website

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    # Step 1: Checkout the code
    - name: Checkout code
      uses: actions/checkout@v3

    # Step 2: Validate HTML files
    - name: Validate HTML
      uses: chrisderivaux/html-validator-action@v1
      with:
        directory: ./

    # Step 3: Validate CSS files
    - name: Validate CSS
      run: |
        for file in $(find . -name '*.css'); do
          curl -X POST -H "Content-Type: text/css" --data-binary @$file https://jigsaw.w3.org/css-validator/validator
        done

  deploy:
    runs-on: ubuntu-latest
    needs: build

    steps:
    # Step 1: Checkout the code
    - name: Checkout code
      uses: actions/checkout@v3

    # Step 2: Deploy to GitHub Pages
    - name: Deploy to GitHub Pages
      uses: peaceiris/actions-gh-pages@v3
      with:
        github_token: ${{ secrets.GITHUB_TOKEN }}
        publish_dir: ./ # The directory to deploy
